version: '3.7'
services:
  promusic-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    hostname: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=promusic
    ports:
      - '5438:5432'
    networks:
      - promusic
  promusic-api:
    image: ${COMPOSE_PROJECT_NAME}-api
    container_name: ${COMPOSE_PROJECT_NAME}-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - promusic-db
    networks:
      - promusic
networks:
  promusic:
    external:
      name: promusic